#WRITTEN BY MOHAMMAD ASADOLAHI  
Mohammad.E.Asadolahi@gmail.com  
https://github.com/mohammadAsadolahi  

In [22]:
import tensorflow as tf
import numpy as np

class NN:
  def __init__(self,layers=[3,3,2,1],activations=None):
    self.W=[]
    self.B=[]
    self.a=[]
    if activations:
      self.a=activations
    else:
      for i in  range(len(layers)-2):
        self.a.append(tf.nn.relu)
    self.a.append(lambda x:tf.multiply(1,x))
    for i in range(len(layers)-1):
      self.W.append(tf.Variable(tf.random.uniform([layers[i+1],layers[i]],minval=-1,maxval=1),dtype=tf.float32))
      self.B.append(tf.Variable(tf.random.uniform([layers[i+1],1],minval=-1,maxval=1),dtype=tf.float32))
  def predict(self,X):
    Z=tf.Variable(X,dtype=tf.float32)
    for w,b,a in zip(self.W,self.B,self.a):
      Z=tf.add(tf.matmul(w,Z),b)
      Z=a(Z)
    return Z
  def loss(self,Y_pred,Y_target):
    return tf.reduce_mean(tf.square(Y_pred-Y_target))
  def fit(self,X,Y,epoch,lr=0.001):
    for i in range(epoch):
      with tf.GradientTape() as tape:
        cost=self.loss(self.predict(X),Y)
        gradients=tape.gradient(cost,[self.W,self.B])
        for dw,db,w,b in zip(gradients[0],gradients[1],self.W,self.B):
          w.assign_sub(dw*lr)
          b.assign_sub(db*lr)
      if (i%100)==0:
        print(f"epoch:{i}  loss:",cost.numpy())

define and train neural net with two data  
leads to overfit!!! (but our purpose is education of how the step of forward propagation and backpropagation are)

In [23]:
neuralNet=NN()
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
y=np.array([11,30,48])
y-neuralNet.predict(x).numpy()

array([[14.74583817, 34.25332355, 52.76080894]])

In [24]:
neuralNet.fit(X=x,Y=y,epoch=3000,lr=0.0005)
print(neuralNet.predict(x).numpy())

epoch:0  loss: 1391.4777
epoch:100  loss: 63.793793
epoch:200  loss: 27.957956
epoch:300  loss: 65.42758
epoch:400  loss: 39.16231
epoch:500  loss: 22.855268
epoch:600  loss: 13.270038
epoch:700  loss: 7.7132173
epoch:800  loss: 4.5012145
epoch:900  loss: 2.6421337
epoch:1000  loss: 1.5637202
epoch:1100  loss: 0.9365754
epoch:1200  loss: 0.5710098
epoch:1300  loss: 0.35744652
epoch:1400  loss: 0.23255616
epoch:1500  loss: 0.15942454
epoch:1600  loss: 0.11652816
epoch:1700  loss: 0.09137399
epoch:1800  loss: 0.076596856
epoch:1900  loss: 0.06792115
epoch:2000  loss: 0.06281599
epoch:2100  loss: 0.059821036
epoch:2200  loss: 0.05806024
epoch:2300  loss: 0.057030678
epoch:2400  loss: 0.056421045
epoch:2500  loss: 0.056064453
epoch:2600  loss: 0.055852298
epoch:2700  loss: 0.055730287
epoch:2800  loss: 0.05565868
epoch:2900  loss: 0.05561607
[[11.162473 29.660816 48.159157]]


In [25]:
print(neuralNet.predict(x).numpy())

[[11.162473 29.660816 48.159157]]


In [29]:
x=np.array([[10],[11],[12]])
print(neuralNet.predict(x).numpy())

[[211.37775]]
